name: Build Windows EXE
 
on:
  # 아래는 GitHub Actions 실행 조건
  # 워크플로를 수동 실행하거나(main 브랜치에 push할 때 자동 실행)
  workflow_dispatch:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: windows-latest  # 윈도우 환경에서 실행
 
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
 
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.6'  # 필요한 Python 버전
 
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install pyinstaller moviepy==1.0.3  # 여기에 설치가 필요한 패키지 추가 없으면 안넣어도 됨
 
    - name: Build EXE
      run:
        
        pyinstaller --onefile --noconsole video_generator_for_deploy.py
        #  여기 파일명을 바꿔주면 다른 파일도 빌드 가능함! (로컬에서 stockreturn/stock.py 빌드)
        # 예: 만약 `subfolder/my_tool.py` 라는 파일을 EXE로 만들고 싶다면:
        # pyinstaller --onefile --noconsole subfolder/my_tool.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build              # 다운로드할 압축파일 이름
        path: dist/test.exe         # 빌드된 exe 파일 경로
